# ***Final analysis***

## Primeras etapas

## **Modelos supervizados**

## **Aprendizaje no supervizado**

In [4]:
%load_ext kedro.ipython 
catalog.keys()

The kedro.ipython extension is already loaded. To reload it, use:
  %reload_ext kedro.ipython

[
    'DataSetFIFA22',
    'DataSetFIFA21',
    'DataSetFIFA20',
    'preprocess_fifa_22',
    'preprocess_fifa_21',
    'preprocess_fifa_20',
    'FIFA22_processed_con_transformacion_columns',
    'FIFA21_processed_con_transformacion_columns',
    'FIFA20_processed_con_transformacion_columns',
    'model_input_table',
    'X_train_regression',
    'X_test_regression',
    'y_test_regression',
    'X_train_class',
    'X_test_class',
    'y_train_class',
    'y_test_class',
    'grid_linear_model',
    'grid_linear_multiple_model',
    'grid_svr_model',
    'grid_decision_tree_model',
    'grid_randomforest_model',
    'grid_logistic_model_classification',
    'grid_knn_model_classification',
    'grind_svc_cv_model_classification',
    'grid_decision_tree_model_classification',
    'grid_random_forest_model_classification',
    'y_pred_linear_regression',
    'y_pred_linear_multiple_regression',
    'y_pred_svr',
    'y_pred_decision_tree_regression',
    'y_pred_random_forest_regression',
    'y_pred_logistic_classification',
    'y_pred_knn_classification',
    'y_pred_svc',
    'y_pred_decision_tree_classification',
    'y_pred_random_forest_classification',
    'metrics_linear_simple_regression',
    'metrics_linear_multiple_regression',
    'metrics_svr',
    'metrics_decision_tree_regression',
    'metrics_random_forest_regression',
    'metrics_logistic',
    'metrics_knn_classification',
    'metrics_svc',
    'metrics_decision_tree_classification',
    'metrics_random_forest_classification',
    'report_linear_simple_pred_vs_real',
    'report_linear_simple_residual_plot',
    'report_linear_simple_qq_plot',
    'report_linear_multiple_pred_vs_real',
    'report_linear_multiple_residual_plot',
    'report_linear_multiple_qq_plot',
    'report_svr_pred_vs_real',
    'report_svr_residual_plot',
    'report_svr_qq_plot',
    'report_decision_tree_pred_vs_real',
    'report_decision_tree_residual_plot',
    'report_decision_tree_qq_plot',
    'report_random_forest_pred_vs_real',
    'report_random_forest_residual_plot',
    'report_random_forest_qq_plot',
    'metris_all_models_regression',
    'Reporte_mejor_metrica_modelo_regresion',
    'metris_all_models_clasificacion',
    'Reporte_mejor_metrica_modelo_clasificacion',
    'parameters',
    'params:modelo_logistic_classification',
    'params:modelo_knn_classification',
    'params:svc_classification',
    'params:modelo_decision_tree_classification',
    'params:modelo_random_forest_classification',
    'params:dimensionality_reduction',
    'params:dimensionality_reduction.pca_n_components',
    'params:dimensionality_reduction.umap_method',
    'params:dimensionality_reduction.umap_n_components',
    'params:dimensionality_reduction.umap_random_state',
    'params:clustering',
    'params:clustering.kmeans',
    'params:clustering.kmeans.n_clusters',
    'params:clustering.kmeans.random_state',
    'params:clustering.dbscan',
    'params:clustering.dbscan.eps',
    'params:clustering.dbscan.min_samples',
    'params:clustering.hierarchical',
    'params:clustering.hierarchical.n_clusters',
    'params:clustering.hierarchical.affinity',
    'params:clustering.hierarchical.linkage',
    'params:model_options_regression',
    'params:model_options_regression.test_size',
    'params:model_options_regression.random_state',
    'params:model_options_regression.features',
    'params:model_options_regression.target',
    'params:_linear_param_grid',
    'params:_linear_param_grid.fit_intercept',
    'params:_linear_param_grid.copy_X',
    'params:_linear_param_grid.n_jobs',
    'params:_dt_param_grid',
    'params:_dt_param_grid.max_depth',
    'params:_dt_param_grid.min_samples_split',
    'params:_rf_param_grid',
    'params:_rf_param_grid.n_estimators',
    'params:_rf_param_grid.max_depth',
    'params:_rf_param_grid.min_samples_split',
    'params:_svr_param_grid',
    'params:_svr_param_grid.kernel',
    'params:_svr_param_grid.C',
    'params:_svr_param_grid.gamma',
    'params:prediction_columns',
    'params:prediction_columns.linear_simple',
    'params:prediction_columns.linear_multiple',
    'params:prediction_columns.svr',
    'params:prediction_columns.decision_tree',
    'params:prediction_columns.random_forest',
    'params:name_report_regression',
    'params:name_report_regression.linear_simple',
    'params:name_report_regression.linear_multiple',
    'params:name_report_regression.svr',
    'params:name_report_regression.decision_tree',
    'params:name_report_regression.random_forest',
    'params:model_options_classification',
    'params:model_options_classification.test_size',
    'params:model_options_classification.random_state',
    'params:model_options_classification.stratify',
    'params:model_options_classification.features',
    'params:model_options_classification.target',
    'params:_logistic_param_grid',
    'params:_logistic_param_grid.logistic__penalty',
    'params:_logistic_param_grid.logistic__C',
    'params:_logistic_param_grid.logistic__solver',
    'params:_logistic_param_grid.logistic__max_iter',
    'params:_logistic_param_grid.logistic__class_weight',
    'params:_knn_param_grid',
    'params:_knn_param_grid.knn__n_neighbors',
    'params:_knn_param_grid.knn__weights',
    'params:_knn_param_grid.knn__metric',
    'params:_knn_param_grid.knn__algorithm',
    'params:_knn_param_grid.knn__p',
    'params:_svc_param_grid',
    'params:_svc_param_grid.svc__C',
    'params:_svc_param_grid.svc__kernel',
    'params:_svc_param_grid.svc__gamma',
    'params:_svc_param_grid.svc__degree',
    'params:_decision_tree_param_grid',
    'params:_decision_tree_param_grid.criterion',
    'params:_decision_tree_param_grid.max_depth',
    'params:_decision_tree_param_grid.min_samples_split',
    'params:_decision_tree_param_grid.min_samples_leaf',
    'params:_decision_tree_param_grid.splitter',
    'params:_decision_tree_param_grid.class_weight',
    'params:_random_forest_param_grid',
    'params:_random_forest_param_grid.n_estimators',
    'params:_random_forest_param_grid.criterion',
    'params:_random_forest_param_grid.max_depth',
    'params:_random_forest_param_grid.min_samples_split',
    'params:_random_forest_param_grid.min_samples_leaf',
    'params:_random_forest_param_grid.bootstrap',
    'params:_random_forest_param_grid.class_weight',
    'params:_random_forest_param_grid.random_state',
    'params:modelo_linear_regression',
    'params:modelo_linear_multiple_regression',
    'params:modelo_svr_regression',
    'params:modelo_decision_tree_regression',
    'params:modelo_grid_randomforest_regression',
    'params:classification_columns',
    'params:classification_columns.logistic_classification',
    'params:classification_columns.knn',
    'params:classification_columns.svc',
    'params:classification_columns.decision_tree',
    'params:classification_columns.random_forest',
    'pca_output',
    'umap_dataset',
    'model_input_table_with_pca',
    'model_input_PCA_and_best_clusters'
]

## **Etapa 1:** analisis y generacion de notebook no supervizados

Resultados obtenidos

conclusiones

## **Etapa 2:** Generacion de pipelines, componentes y datasets

## Componentes generados

- Al realizar la etapa 1 para obtener los componentes necesarios, dentro del proyecto se genera un pipeline para generar xd los componentes.

- Por temas de tiempo y se escoje PCA para la el uso de reduccion de dimencionalidad debido a la calidad del analisis y interpretaciones realizadas. Mientras que umap no se considerara por falta de interpretaciones y conocimiento teorico.

In [5]:
pca_output = catalog.load("pca_output")
umap_dataset = catalog.load("umap_dataset")

model_input_table_with_pca = catalog.load("model_input_table_with_pca")

model_input_table_with_pca_bcluster =  catalog.load("model_input_PCA_and_best_clusters")

[03/19/26 23:06:31] INFO     Loading data from pca_output (ParquetDataset)...                  ]8;id=513797;file://C:\Users\brand\Downloads\Proyecto_ML_Kedro\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=264777;file://C:\Users\brand\Downloads\Proyecto_ML_Kedro\.venv\Lib\site-packages\kedro\io\data_catalog.py#1046\1046]8;;\

                    INFO     Loading data from umap_dataset (ParquetDataset)...                ]8;id=330695;file://C:\Users\brand\Downloads\Proyecto_ML_Kedro\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=616;file://C:\Users\brand\Downloads\Proyecto_ML_Kedro\.venv\Lib\site-packages\kedro\io\data_catalog.py#1046\1046]8;;\

                    INFO     Loading data from model_input_table_with_pca (ParquetDataset)...  ]8;id=472020;file://C:\Users\brand\Downloads\Proyecto_ML_Kedro\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=698855;file://C:\Users\brand\Downloads\Proyecto_ML_Kedro\.venv\Lib\site-packages\kedro\io\data_catalog.py#1046\1046]8;;\

[03/19/26 23:06:32] INFO     Loading data from model_input_PCA_and_best_clusters               ]8;id=798646;file://C:\Users\brand\Downloads\Proyecto_ML_Kedro\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=785322;file://C:\Users\brand\Downloads\Proyecto_ML_Kedro\.venv\Lib\site-packages\kedro\io\data_catalog.py#1046\1046]8;;\
                             (ParquetDataset)...

In [6]:
pca_output

,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,PC11,PC12,PC13,PC14
0,2.268247e+08,5.210757e+05,-25633.939379,-810.858724,7.392521,-112.322835,-11.152312,32.024574,-24.916042,33.482220,12.867966,-33.501654,23.336811,7.323134
1,1.788551e+08,8.972320e+06,-100995.195306,-712.146317,65.775538,-96.560635,0.470820,20.786049,-13.547765,13.156849,14.048992,-18.103810,16.188043,-3.259164
2,9.511618e+07,-2.370829e+06,19212.371354,85.762760,-56.809527,39.138589,28.440922,-1.955973,4.112363,11.248621,7.004659,-14.077261,7.818414,6.905728
3,7.967980e+07,-2.840922e+06,-51728.196834,360.067640,29.114659,33.097133,-8.135818,18.824677,-3.355041,7.968906,6.493852,-12.381979,10.861407,1.934038
4,2.087503e+08,1.041681e+07,-119232.302054,-973.182807,81.794115,-124.834032,-30.832098,30.684933,-29.545999,24.889497,4.256433,-12.020992,21.134969,16.738983
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44962,-6.211912e+06,-7.356128e+04,965.972029,-838.990514,-13.133335,-13.754607,-6.399361,33.154784,-13.987108,2.443305,4.624520,-10.652990,4.702210,-0.954861
44963,-6.267664e+06,-6.165405e+04,1001.041431,-847.474132,-18.346171,-11.246244,-2.125970,41.716093,-25.031245,-2.734461,-1.263505,-3.341280,6.125072,4.699442
44964,-6.260560e+06,-6.533454e+04,-2998.078646,-845.092903,10.211358,-12.349897,0.036248,30.411889,-26.538583,2.710983,8.922294,-6.154706,0.048761,-0.826348
44965,-6.178003e+06,-7.981709e+04,942.151736,-856.239924,5.397535,-18.053174,0.795804,60.166638,10.736437,-10.982797,7.853435,-4.628041,1.761322,1.681543
44966,-6.228794e+06,-6.484370e+04,963.841374,-871.649768,-15.697403,-21.471573,-4.916521,29.245147,-20.901047,5.711850,2.432550,-11.199673,8.748638,3.230708

In [7]:
umap_dataset

         UMAP_1     UMAP_2
0      5.573100  16.154810
1      5.674626  16.066219
2      6.761441  15.063475
3      7.354212  14.468845
4      5.577801  16.150534
...         ...        ...
44962  0.694308   9.511245
44963  1.107728  10.825798
44964  1.253667  10.687239
44965  0.637696   8.426234
44966  1.019657   9.814875

[44967 rows x 2 columns]

Se suma las columnas del dataframe procesado inicial de los modelos y los componentes, esta es  una opcion ya que en otros casos se puede usar solamente los componentes como entrada de datos para los modelos.

In [8]:
model_input_table_with_pca

,Age,Overall,Potential,Special,International Reputation,Weak Foot,Skill Moves,Jersey Number,Crossing,Finishing,...,PC5,PC6,PC7,PC8,PC9,PC10,PC11,PC12,PC13,PC14
0,26,88,89,2341,3.0,3.0,4.0,18.0,87.0,83.0,...,7.392521,-112.322835,-11.152312,32.024574,-24.916042,33.482220,12.867966,-33.501654,23.336811,7.323134
1,26,87,88,2314,4.0,4.0,3.0,8.0,75.0,82.0,...,65.775538,-96.560635,0.470820,20.786049,-13.547765,13.156849,14.048992,-18.103810,16.188043,-3.259164
2,34,88,88,2307,5.0,4.0,3.0,9.0,80.0,93.0,...,-56.809527,39.138589,28.440922,-1.955973,4.112363,11.248621,7.004659,-14.077261,7.818414,6.905728
3,29,84,84,2292,2.0,3.0,4.0,19.0,87.0,66.0,...,29.114659,33.097133,-8.135818,18.824677,-3.355041,7.968906,6.493852,-12.381979,10.861407,1.934038
4,26,89,90,2283,4.0,4.0,3.0,6.0,91.0,68.0,...,81.794115,-124.834032,-30.832098,30.684933,-29.545999,24.889497,4.256433,-12.020992,21.134969,16.738983
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44962,17,50,72,773,1.0,2.0,1.0,41.0,11.0,6.0,...,-13.133335,-13.754607,-6.399361,33.154784,-13.987108,2.443305,4.624520,-10.652990,4.702210,-0.954861
44963,19,50,60,764,1.0,2.0,1.0,39.0,12.0,8.0,...,-18.346171,-11.246244,-2.125970,41.716093,-25.031245,-2.734461,-1.263505,-3.341280,6.125072,4.699442
44964,18,50,61,757,1.0,3.0,1.0,30.0,13.0,6.0,...,10.211358,-12.349897,0.036248,30.411889,-26.538583,2.710983,8.922294,-6.154706,0.048761,-0.826348
44965,18,51,70,755,1.0,2.0,1.0,78.0,11.0,8.0,...,5.397535,-18.053174,0.795804,60.166638,10.736437,-10.982797,7.853435,-4.628041,1.761322,1.681543
44966,17,48,63,740,1.0,2.0,1.0,35.0,10.0,7.0,...,-15.697403,-21.471573,-4.916521,29.245147,-20.901047,5.711850,2.432550,-11.199673,8.748638,3.230708

## Data +  PCA + clustering 

- Segun nuestro evaluador o profesor, nos piden que integremos al menos un clustering como caracteristica y realizar una comparacion de las metricas de los modedelos supervizavos vs modelos supervizados + tecnincas de modelos no supervizados.

¿Hay una mejora?

In [11]:
#dataset_for_clustering = catalog.load("dataset_for_clustering")
#dataset_with_best_clusters = catalog.load("dataset_with_best_clusters")
reduccion_clustering_dataset_final = catalog.load("model_input_PCA_and_best_clusters")

[03/19/26 23:06:57] INFO     Loading data from model_input_PCA_and_best_clusters               ]8;id=918363;file://C:\Users\brand\Downloads\Proyecto_ML_Kedro\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=497470;file://C:\Users\brand\Downloads\Proyecto_ML_Kedro\.venv\Lib\site-packages\kedro\io\data_catalog.py#1046\1046]8;;\
                             (ParquetDataset)...

Mejor clustering según silhouette: kmeans (score=0.794)

In [ ]:
dataset_with_best_clusters

In [ ]:
dataset_with_best_clusters["clustered_data"].value_counts()

In [12]:
reduccion_clustering_dataset_final

,Age,Overall,Potential,Special,International Reputation,Weak Foot,Skill Moves,Jersey Number,Crossing,Finishing,...,PC6,PC7,PC8,PC9,PC10,PC11,PC12,PC13,PC14,clustered_data
0,26,88,89,2341,3.0,3.0,4.0,18.0,87.0,83.0,...,-112.322835,-11.152312,32.024574,-24.916042,33.482220,12.867966,-33.501654,23.336811,7.323134,2
1,26,87,88,2314,4.0,4.0,3.0,8.0,75.0,82.0,...,-96.560635,0.470820,20.786049,-13.547765,13.156849,14.048992,-18.103810,16.188043,-3.259164,2
2,34,88,88,2307,5.0,4.0,3.0,9.0,80.0,93.0,...,39.138589,28.440922,-1.955973,4.112363,11.248621,7.004659,-14.077261,7.818414,6.905728,1
3,29,84,84,2292,2.0,3.0,4.0,19.0,87.0,66.0,...,33.097133,-8.135818,18.824677,-3.355041,7.968906,6.493852,-12.381979,10.861407,1.934038,1
4,26,89,90,2283,4.0,4.0,3.0,6.0,91.0,68.0,...,-124.834032,-30.832098,30.684933,-29.545999,24.889497,4.256433,-12.020992,21.134969,16.738983,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44962,17,50,72,773,1.0,2.0,1.0,41.0,11.0,6.0,...,-13.754607,-6.399361,33.154784,-13.987108,2.443305,4.624520,-10.652990,4.702210,-0.954861,0
44963,19,50,60,764,1.0,2.0,1.0,39.0,12.0,8.0,...,-11.246244,-2.125970,41.716093,-25.031245,-2.734461,-1.263505,-3.341280,6.125072,4.699442,0
44964,18,50,61,757,1.0,3.0,1.0,30.0,13.0,6.0,...,-12.349897,0.036248,30.411889,-26.538583,2.710983,8.922294,-6.154706,0.048761,-0.826348,0
44965,18,51,70,755,1.0,2.0,1.0,78.0,11.0,8.0,...,-18.053174,0.795804,60.166638,10.736437,-10.982797,7.853435,-4.628041,1.761322,1.681543,0
44966,17,48,63,740,1.0,2.0,1.0,35.0,10.0,7.0,...,-21.471573,-4.916521,29.245147,-20.901047,5.711850,2.432550,-11.199673,8.748638,3.230708,0

In [ ]:
analisis inteprretaciones 


# uso